---
version: '3.4'
services:

  node.opendata.0.org:
    cap_add:
      - NET_ADMIN
    image: bode-pki-besu:latest
    container_name: node.opendata.0.org
    volumes:
      - ./docker/config/node-operator/all/config.toml:/opt/besu/config/config.toml
      - ./docker/config/node-operator/all/genesis.json:/opt/besu/config/genesis.json
      - ./docker/config/node-operator/opendata-0/key:/opt/besu/keys/key
      - ./docker/data/node-operator/opendata-0/data:/opt/besu/data
    ports:
      - 8545:8545
      - 8546:8546
    networks:
      blockchain-based-opendata-ecosystem:
        ipv4_address: 176.0.1.1

  node.opendata.1.org:
    cap_add:
      - NET_ADMIN
    image: bode-pki-besu:latest
    container_name: node.opendata.1.org
    volumes:
      - ./docker/config/node-operator/all/config.toml:/opt/besu/config/config.toml
      - ./docker/config/node-operator/all/genesis.json:/opt/besu/config/genesis.json
      - ./docker/config/node-operator/opendata-1/key:/opt/besu/keys/key
      - ./docker/data/node-operator/opendata-1/data:/opt/besu/data
    ports:
      - 8547:8545
      - 8548:8546
    networks:
      blockchain-based-opendata-ecosystem:
        ipv4_address: 176.0.1.2

  node.opendata.2.org:
    cap_add:
      - NET_ADMIN
    image: bode-pki-besu:latest
    container_name: node.opendata.2.org
    volumes:
      - ./docker/config/node-operator/all/config.toml:/opt/besu/config/config.toml
      - ./docker/config/node-operator/all/genesis.json:/opt/besu/config/genesis.json
      - ./docker/config/node-operator/opendata-2/key:/opt/besu/keys/key
      - ./docker/data/node-operator/opendata-2/data:/opt/besu/data
    ports:
      - 8549:8545
      - 8550:8546
    networks:
      blockchain-based-opendata-ecosystem:
        ipv4_address: 176.0.1.3

  node.opendata.3.org:
    cap_add:
      - NET_ADMIN
    image: bode-pki-besu:latest
    container_name: node.opendata.3.org
    volumes:
      - ./docker/config/node-operator/all/config.toml:/opt/besu/config/config.toml
      - ./docker/config/node-operator/all/genesis.json:/opt/besu/config/genesis.json
      - ./docker/config/node-operator/opendata-3/key:/opt/besu/keys/key
      - ./docker/data/node-operator/opendata-3/data:/opt/besu/data
    ports:
      - 8551:8545
      - 8552:8546
    networks:
      blockchain-based-opendata-ecosystem:
        ipv4_address: 176.0.1.4

  node.opendata.4.org:
    cap_add:
      - NET_ADMIN
    image: bode-pki-besu:latest
    container_name: node.opendata.4.org
    volumes:
      - ./docker/config/node-operator/all/config.toml:/opt/besu/config/config.toml
      - ./docker/config/node-operator/all/genesis.json:/opt/besu/config/genesis.json
      - ./docker/config/node-operator/opendata-4/key:/opt/besu/keys/key
      - ./docker/data/node-operator/opendata-4/data:/opt/besu/data
    ports:
      - 8553:8545
      - 8554:8546
    networks:
      blockchain-based-opendata-ecosystem:
        ipv4_address: 176.0.1.5

  node.opendata.5.org:
    cap_add:
      - NET_ADMIN
    image: bode-pki-besu:latest
    container_name: node.opendata.5.org
    volumes:
      - ./docker/config/node-operator/all/config.toml:/opt/besu/config/config.toml
      - ./docker/config/node-operator/all/genesis.json:/opt/besu/config/genesis.json
      - ./docker/config/node-operator/opendata-5/key:/opt/besu/keys/key
      - ./docker/data/node-operator/opendata-5/data:/opt/besu/data
    ports:
      - 8555:8545
      - 8556:8546
    networks:
      blockchain-based-opendata-ecosystem:
        ipv4_address: 176.0.1.6

  node.opendata.6.org:
    cap_add:
      - NET_ADMIN
    image: bode-pki-besu:latest
    container_name: node.opendata.6.org
    volumes:
      - ./docker/config/node-operator/all/config.toml:/opt/besu/config/config.toml
      - ./docker/config/node-operator/all/genesis.json:/opt/besu/config/genesis.json
      - ./docker/config/node-operator/opendata-6/key:/opt/besu/keys/key
      - ./docker/data/node-operator/opendata-6/data:/opt/besu/data
    ports:
      - 8557:8545
      - 8558:8546
    networks:
      blockchain-based-opendata-ecosystem:
        ipv4_address: 176.0.1.7

  node.opendata.7.org:
    cap_add:
      - NET_ADMIN
    image: bode-pki-besu:latest
    container_name: node.opendata.7.org
    volumes:
      - ./docker/config/node-operator/all/config.toml:/opt/besu/config/config.toml
      - ./docker/config/node-operator/all/genesis.json:/opt/besu/config/genesis.json
      - ./docker/config/node-operator/opendata-7/key:/opt/besu/keys/key
      - ./docker/data/node-operator/opendata-7/data:/opt/besu/data
    ports:
      - 8559:8545
      - 8560:8546
    networks:
      blockchain-based-opendata-ecosystem:
        ipv4_address: 176.0.1.8

  node.opendata.8.org:
    cap_add:
      - NET_ADMIN
    image: bode-pki-besu:latest
    container_name: node.opendata.8.org
    volumes:
      - ./docker/config/node-operator/all/config.toml:/opt/besu/config/config.toml
      - ./docker/config/node-operator/all/genesis.json:/opt/besu/config/genesis.json
      - ./docker/config/node-operator/opendata-8/key:/opt/besu/keys/key
      - ./docker/data/node-operator/opendata-8/data:/opt/besu/data
    ports:
      - 8561:8545
      - 8562:8546
    networks:
      blockchain-based-opendata-ecosystem:
        ipv4_address: 176.0.1.9

  node.opendata.9.org:
    cap_add:
      - NET_ADMIN
    image: bode-pki-besu:latest
    container_name: node.opendata.9.org
    volumes:
      - ./docker/config/node-operator/all/config.toml:/opt/besu/config/config.toml
      - ./docker/config/node-operator/all/genesis.json:/opt/besu/config/genesis.json
      - ./docker/config/node-operator/opendata-9/key:/opt/besu/keys/key
      - ./docker/data/node-operator/opendata-9/data:/opt/besu/data
    ports:
      - 8563:8545
      - 8564:8546
    networks:
      blockchain-based-opendata-ecosystem:
        ipv4_address: 176.0.1.10

  authorization-system.na.org:
    cap_add:
      - NET_ADMIN
    image: bode-pki-authorization-system:latest
    container_name: authorization-system.na.org
    volumes:
      - ./docker/config/network-authority/config.json:/usr/verticles/conf/config.json
      - ./docker/data/network-authority/data:/usr/verticles/store
    networks:
      blockchain-based-opendata-ecosystem:
        ipv4_address: 176.0.1.11
    ports:
      - 8080:8080
      - 8081:8081
  
  authorization-system.opendata.0.org:
    cap_add:
      - NET_ADMIN
    image: bode-pki-authorization-system:latest
    container_name: authorization-system.opendata.0.org
    volumes:
      - ./docker/config/node-operator/opendata-0/config.json:/usr/verticles/conf/config.json
      - ./docker/data/node-operator/opendata-0/data:/usr/verticles/store
    networks:
      blockchain-based-opendata-ecosystem:
        ipv4_address: 176.0.1.12
    ports:
      - 8082:8080
      - 8083:8081

  authorization-system.opendata.1.org:
    cap_add:
      - NET_ADMIN
    image: bode-pki-authorization-system:latest
    container_name: authorization-system.opendata.1.org
    volumes:
      - ./docker/config/node-operator/opendata-1/config.json:/usr/verticles/conf/config.json
      - ./docker/data/node-operator/opendata-1/data:/usr/verticles/store
    networks:
      blockchain-based-opendata-ecosystem:
        ipv4_address: 176.0.1.13
    ports:
      - 8084:8080
      - 8085:8081

  authorization-system.opendata.2.org:
    cap_add:
      - NET_ADMIN
    image: bode-pki-authorization-system:latest
    container_name: authorization-system.opendata.2.org
    volumes:
      - ./docker/config/node-operator/opendata-2/config.json:/usr/verticles/conf/config.json
      - ./docker/data/node-operator/opendata-2/data:/usr/verticles/store
    networks:
      blockchain-based-opendata-ecosystem:
        ipv4_address: 176.0.1.14
    ports:
      - 8086:8080
      - 8087:8081

  authorization-system.opendata.3.org:
    cap_add:
      - NET_ADMIN
    image: bode-pki-authorization-system:latest
    container_name: authorization-system.opendata.3.org
    volumes:
      - ./docker/config/node-operator/opendata-3/config.json:/usr/verticles/conf/config.json
      - ./docker/data/node-operator/opendata-3/data:/usr/verticles/store
    networks:
      blockchain-based-opendata-ecosystem:
        ipv4_address: 176.0.1.15
    ports:
      - 8088:8080
      - 8089:8081

  authorization-system.opendata.4.org:
    cap_add:
      - NET_ADMIN
    image: bode-pki-authorization-system:latest
    container_name: authorization-system.opendata.4.org
    volumes:
      - ./docker/config/node-operator/opendata-4/config.json:/usr/verticles/conf/config.json
      - ./docker/data/node-operator/opendata-4/data:/usr/verticles/store
    networks:
      blockchain-based-opendata-ecosystem:
        ipv4_address: 176.0.1.16
    ports:
      - 8090:8080
      - 8091:8081

  authorization-system.opendata.5.org:
    cap_add:
      - NET_ADMIN
    image: bode-pki-authorization-system:latest
    container_name: authorization-system.opendata.5.org
    volumes:
      - ./docker/config/node-operator/opendata-5/config.json:/usr/verticles/conf/config.json
      - ./docker/data/node-operator/opendata-5/data:/usr/verticles/store
    networks:
      blockchain-based-opendata-ecosystem:
        ipv4_address: 176.0.1.17
    ports:
      - 8092:8080
      - 8093:8081

  authorization-system.opendata.6.org:
    cap_add:
      - NET_ADMIN
    image: bode-pki-authorization-system:latest
    container_name: authorization-system.opendata.6.org
    volumes:
      - ./docker/config/node-operator/opendata-6/config.json:/usr/verticles/conf/config.json
      - ./docker/data/node-operator/opendata-6/data:/usr/verticles/store
    networks:
      blockchain-based-opendata-ecosystem:
        ipv4_address: 176.0.1.18
    ports:
      - 8094:8080
      - 8095:8081

  authorization-system.opendata.7.org:
    cap_add:
      - NET_ADMIN
    image: bode-pki-authorization-system:latest
    container_name: authorization-system.opendata.7.org
    volumes:
      - ./docker/config/node-operator/opendata-7/config.json:/usr/verticles/conf/config.json
      - ./docker/data/node-operator/opendata-7/data:/usr/verticles/store
    networks:
      blockchain-based-opendata-ecosystem:
        ipv4_address: 176.0.1.19
    ports:
      - 8096:8080
      - 8097:8081

  authorization-system.opendata.8.org:
    cap_add:
      - NET_ADMIN
    image: bode-pki-authorization-system:latest
    container_name: authorization-system.opendata.8.org
    volumes:
      - ./docker/config/node-operator/opendata-8/config.json:/usr/verticles/conf/config.json
      - ./docker/data/node-operator/opendata-8/data:/usr/verticles/store
    networks:
      blockchain-based-opendata-ecosystem:
        ipv4_address: 176.0.1.20
    ports:
      - 8098:8080
      - 8099:8081

  authorization-system.opendata.9.org:
    cap_add:
      - NET_ADMIN
    image: bode-pki-authorization-system:latest
    container_name: authorization-system.opendata.9.org
    volumes:
      - ./docker/config/node-operator/opendata-9/config.json:/usr/verticles/conf/config.json
      - ./docker/data/node-operator/opendata-9/data:/usr/verticles/store
    networks:
      blockchain-based-opendata-ecosystem:
        ipv4_address: 176.0.1.21
    ports:
      - 8100:8080
      - 8101:8081
  
networks:
  blockchain-based-opendata-ecosystem:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  176.0.0.0/16
        gateway: 176.0.0.1
